name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: koutsie/vitalised-styled-blog-nice@this-release-is-very-important-for-the-endurance-of-the-human-race-also-dark-mode-for-you-buddy-btw-also-i-still-hate-js
        with:
          branch: gh-pages # Optional branch for GitHub Pages

