name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: koutsie/vitalised-styled-blog-nice@i-really-love-to-draft-new-releases-all-the-time-vitalsied
        with:
          branch: gh-pages # Optional branch for GitHub Pages

