name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: koutsie/vitalised-styled-blog-nice@another-very-long-tag-for-no-fucking-reason-because-i-reallly-love-our-workflow-here-at-vitalised-industries-and-also-is-there-really-no-limit
        with:
          branch: gh-pages # Optional branch for GitHub Pages

